apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: nikitamatrosov/test-frontend:minikube
        imagePullPolicy: Always
        name: test-frontend
        ports:
        - containerPort: 80
